# Generated by Django 5.2.14 on 2026-05-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('specialization', models.CharField(choices=[('battery', 'Battery Specialist'), ('charger', 'Charger / Wiring'), ('general', 'General EV Mechanic'), ('tyre', 'Tyre & Suspension'), ('motor', 'Motor & Drivetrain')], default='general', max_length=30)),
                ('location_text', models.CharField(max_length=500)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('experience_years', models.PositiveIntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='mechanics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_available', '-rating'],
            },
        ),
    ]
