# Generated by Django 5.2.14 on 2026-06-07 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_payment_attempt_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('starter', 'Starter — 500 Bookings / ₹1,000'), ('pro', 'Pro — 1,200 Bookings / ₹2,000')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bookings_total', models.PositiveIntegerField()),
                ('bookings_remaining', models.PositiveIntegerField()),
                ('bookings_used', models.PositiveIntegerField(default=0)),
                ('commission_owed', models.DecimalField(decimal_places=2, default=0, help_text='Total commission the owner owes to the platform (5% of over-limit bookings)', max_digits=12)),
                ('commission_bookings', models.PositiveIntegerField(default=0, help_text='Number of bookings that exceeded the plan limit')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(default='razorpay', max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
